name: Linux Build (Epitech Container)
on: [push, pull_request]

jobs:
  testbox:
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
    runs-on: ubuntu-latest
    container:
      image: epitechcontent/epitest-docker:latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Build
        run: |
          mkdir build && cd build
          cmake ..
          cmake --build .
      - name: CheckBinaryName
        shell: bash
        run: test -f build/bomberman
      - name: Archive production artifact for Linux binary
        uses: actions/upload-artifact@v1
        with:
          name: BombermanLinux
          path: build/bomberman